services:
    idci_barcode.generator:
        class: IDCI\Bundle\BarcodeBundle\Generator\Generator

    idci_barcode.twig.extension:
        class: IDCI\Bundle\BarcodeBundle\Twig\Extensions\Barcode
        arguments:
            - "@idci_barcode.generator"
        tags:
            - { name: twig.extension }
